Document: dapr
Title: Debian dapr Manual
Author: <insert document author here>
Abstract: This manual describes what dapr is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dapr/dapr.sgml.gz

Format: postscript
Files: /usr/share/doc/dapr/dapr.ps.gz

Format: text
Files: /usr/share/doc/dapr/dapr.text.gz

Format: HTML
Index: /usr/share/doc/dapr/html/index.html
Files: /usr/share/doc/dapr/html/*.html
